# errors


## 1.实现

```go
import "errors"
```

errors包实现了创建错误值的函数。

errors包提供了两个函数：New和Errorf。

- New函数用于创建一个新的错误值，该错误值包含给定的错误信息。
- Errorf函数用于创建一个新的错误值，该错误值包含给定的错误信息和格式化参数。


demo1/demo1.go


```go
package demo1

import (
	"errors"
	"fmt"
)

func ErrorUsage() {

	err := errors.New("err: found 1")
	if err != nil {
		fmt.Println(err.Error()) //err: found 1
	}
	err2 := fmt.Errorf("err: %s", "found 2")
	if err2 != nil {
		fmt.Println(err2.Error()) //err: found 2
	}
}

type SelfError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (self SelfError) Error() string {
	return fmt.Sprintf("Code: %d, Message: %s", self.Code, self.Message)
}

func UsageError(value string) error {
	var self SelfError
	if value == "" {
		self.Code = 400
		self.Message = "fail"
		return self
	}
	return nil
}

func UserErrorUsage() {

	err3 := UsageError("")
	if err3 != nil {
		fmt.Println(err3.Error()) //Code: 400, Message: fail
	}

}

```


## 2.编写单元测试

demo1/demo1_test.go


```go
package demo1

import "testing"

func TestErrorUsage(t *testing.T) {
	ErrorUsage()
	UserErrorUsage()
}

```


## 3.测试结果

```sh
D:/Program Files/go/bin/go.exe test -v [D:/golang/go/src/gitee/go-standard-lib/error_demo/demo1]
=== RUN   TestErrorUsage
err: found 1
err: found 2
Code: 400, Message: fail
--- PASS: TestErrorUsage (0.00s)
PASS
ok  	demo1	0.478s
```