# 15.Python 异常处理

什么是异常？
顾名思义，异常就是程序因为某种原因无法正常工作了，比如缩进错误、缺少软件包、环境错误、连接超时等等都会引发异常。

一个健壮的程序应该把所能预知的异常都应做相应的处理，应对一些简单的异常情况，使得更好的保证程序长时间运行。即使出了问题，也可让维护者一眼看出问题所在。

## 1.捕捉异常语法

```python
try:
    expression
except [Except Type]:
    expression
```

如果在执行 try 块里的业务逻辑代码时出现异常，系统自动生成一个异常对象，该异常对象被提交给 Python 解释器，这个过程被称为引发异常。

当 Python 解释器收到异常对象时，会寻找能处理该异常对象的 except 块，如果找到合适的 except 块，则把该异常对象交给该 except 块处理，这个过程被称为捕获异常。

如果 Python 解释器找不到捕获异常的 except 块，则运行时环境终止，Python 解释器也将退出。

## 2.异常类型

常见的异常类型：

| 异常类型           | 用途                                 |
| ------------------ | ------------------------------------ |
| SyntaxError        | 语法错误                             |
| IndentationError   | 缩进错误                             |
| TypeError          | 对象类型与要求不符合                 |
| ImportError        | 模块或包导入错误；一般路径或名称错误 |
| KeyError           | 字典里面不存在的键                   |
| NameError          | 变量不存在                           |
| IndexError         | 下标超出序列范围                     |
| IOError            | 输入/输出异常；一般是无法打开文件    |
| AttributeError     | 对象里没有属性                       |
| KeyboardInterrupt  | 键盘接受到 Ctrl+C                    |
| Exception          | 通用的异常类型；一般会捕捉所有异常   |
| UnicodeEncodeError | 编码错误                             |

内置异常的类层级结构如下：

```shell
BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      +-- SyntaxError
      |    +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- ResourceWarning
```

## 3.异常处理

示例 1： 打印一个没有定义的变量 ，名称错误

异常处理：

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
try:
    print(name)
except NameError:
    print("发生名称错误时，执行的代码")
```

示例 2：字符串与整数计算，类型错误

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
try:
    n = '2' + 2
except TypeError:
    print("发生类型错误时，执行的代码")

```

在上面示例中，我们通过指定异常类型准确的处理，但在实际开发中，往往不知道会引发什么样的异常类型，这时就可以使用 Exception 类型来捕捉所有的异常。

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

try:
    n = '2' + 2
except Exception:
    print("发生错误执行的代码")
```

这样不管是名称错误还是类型错误都可以捕获到进行处理。
在处理异常的同时，也希望能将执行的错误信息打印出来，以便让用户检查。

可以将错误输出通过 as 关键字保存到变量中，再进行打印：

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

try:
    print(name)
except Exception as e:
    print("错误：%s" %e)
    print("发生错误执行的代码")
```

注：except 也可以不指定异常类型，那么会忽略所有的异常类，这样做有风险，它同样会捕捉 Ctrl+C、sys.exit 等的操作，所以使用 except Exception 更好些。

## 4.else 和 finally 语句

### 4.1 else 语句

在异常处理流程中还可以添加一个 else 块，当 try 块没有出现异常时，程序会执行 else 块。

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
name = "hujianli"
try:
    print(name)
except Exception as e:
    print("错误：%s" %e)
    print("发生错误执行的代码")
else:
    print("没有出现异常执行的代码")
```

### 4.2 finally 语句

当 try 块不管是异常，都会执行 finally。一般用于业务逻辑处理完后的清理工作，例如打开一个文件，不管是否操作成功，都应该关闭文件。

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
f = open("computer.txt",encoding="utf8")
try:
    data = f.read()
except Exception as e:
    print("错误：%s" %e)
    print("发生错误执行的代码")
finally:
    f.close()
```

### 4.3 try...except...else...finally

这是一个完整的语句，当一起使用时，使异常处理更加灵活。

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
try:
    print(name)
except Exception as e:
    print("错误：%s" %e)
    print("发生错误执行的代码")
else:
    print("没有出现异常执行的代码")
finally:
    print("最后执行的代码")
```

注：它们语句的顺序必须是 try...except...else...finally，否则语法错误！里面 else 和 finally 是可选的。

## 5.创建自定义异常

raise 语句允许程序员强制发生指定的异常。用来手动抛出一个异常，使用方法：

语法：`raise [exceptionName [(reason)]]`

其中，用 [] 括起来的为可选参数，其作用是指定抛出的异常名称，以及异常信息的相关描述。如果可选参数全部省略，则 raise 会把当前错误原样抛出；如果仅省略 (reason)，则在抛出异常时，将不附带任何的异常描述信息。

也就是说，raise 语句有如下三种常用的用法：

- raise：单独一个 raise。该语句引发当前上下文中捕获的异常（比如在 except 块中），或默认引发 RuntimeError 异常。
- raise 异常类名称：raise 后带一个异常类名称，表示引发执行类型的异常。
- raise 异常类名称(描述信息)：在引发指定类型的异常的同时，附带异常的描述信息。

```python
try:
    raise
except Exception as e:
    print("自定义异常类错误: %s" %e)
```

raise 唯一的参数就是要抛出的异常。这个参数必须是一个异常实例或者是一个异常类（Exception 子类）

例如：抛出一个指定的异常

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
name = "hujianli"
try:
    print(name)
    raise NameError("程序猿抛出的异常")
except Exception as e:
    print("错误：%s" % e)
    print("发生错误执行的代码")
else:
    print("没有出现异常执行的代码")
finally:
    print("最后执行的代码")

```

raise 参数必须是一个异常的实例或 Exception 子类。

上面用的 Exception 子类，那么我定义一个异常的实例，需要继承 Exception 类：

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
class MyError(Exception):
    def __init__(self, msg):
        self.msg = msg

    def __str__(self):  # __str__自动打印这个方法 return 的数据
        return self.msg


try:
    if 1 != 2:
        raise MyError("手动引发异常")
except MyError as e:
    print("自定义异常类错误: %s" % e)
```


```python
class NetworkError(Exception):
    pass

class HostnameError(NetworkError):
    pass

class TimeoutError(NetworkError):
    pass

class ProtocolError(NetworkError):
    pass
```


然后用户就可以像通常那样使用这些异常了，例如：

```sh
try:
    msg = s.recv()
except TimeoutError as e:
    ...
except ProtocolError as e:
    ...
```




## 6.traceback-异常和调用堆栈跟踪

https://docs.python.org/zh-cn/3.10/library/traceback.html


如果你的代码所在的环境很难获取交互shell（比如在某个服务器上面）， 通常可以捕获异常后自己打印跟踪信息。例如：



```python
#!/usr/bin/env python
# -*- coding:utf8 -*-
# filename: 异常堆栈跟踪2.py
import traceback


class SelfException(Exception):
    pass


def main():
    firstMethod()


def firstMethod():
    SecondMethod()


def SecondMethod():
    thirdMethod()


def thirdMethod():
    raise SecondMethod("自定义异常信息")


try:
    main()
except:
    # 捕获异常信息，并将异常信息输出到控制台
    traceback.print_exc()
    # 捕获异常信息，并将异常信息输出到指定文件中
    traceback.print_exc(file=open("log.txt", "a", encoding="utf-8"))
```


```python
import traceback 
try: 
    10 / 0 
except Exception as e: 
    traceback.print_exc() # 命令行输出堆栈信息
    info = traceback.format_exc() # 保存堆栈信息到变量， 内容与上面语句一致
    print(info)
```